#!/usr/bin/env python3
"""Stamp build provenance into the site.

Writes `_variables.yml`, which Quarto exposes to pages as `{{< var … >}}`.
Run before `quarto render`.

A framework arguing that provenance must travel with an artifact should carry
its own. Every page therefore states the version, the exact commit it was built
from, and the build date — so a reader can tell precisely what they are looking
at, and a study citing a version can be checked against it.
"""

from __future__ import annotations

import os
import re
import subprocess
from datetime import date, datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://acquire-framework.github.io"


def git(*args: str, default: str = "unknown") -> str:
    try:
        out = subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
        )
        return out.stdout.strip() or default
    except (subprocess.CalledProcessError, FileNotFoundError):
        return default


def package_version() -> str:
    text = (ROOT / "acquire" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    if not match:
        raise SystemExit("could not read __version__ from acquire/__init__.py")
    return match.group(1)


def build_date() -> str:
    """Honour SOURCE_DATE_EPOCH so a rebuild of a tag is reproducible."""
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch:
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc).date().isoformat()
    return date.today().isoformat()


def main() -> None:
    version = package_version()
    commit = git("rev-parse", "HEAD")
    short = git("rev-parse", "--short", "HEAD")
    # Set by the workflow when building a tagged release; absent on main builds.
    ref = os.environ.get("ACQUIRE_RELEASE_TAG", "").strip()
    is_release = bool(ref)

    # A versioned build is served from /v<version>/ and is immutable; the root
    # always serves the newest release.
    base = f"{SITE_URL}/v{version}" if is_release else SITE_URL

    lines = [
        "# Generated by tools/stamp_version.py — do not edit.",
        f'version: "{version}"',
        f'commit: "{commit}"',
        f'commit_short: "{short}"',
        f'build_date: "{build_date()}"',
        f"is_release: {str(is_release).lower()}",
        f'release_tag: "{ref}"',
        f'permalink: "{base}"',
        f'site_url: "{SITE_URL}"',
        f'repo: "https://github.com/acquire-framework/acquire-framework.github.io"',
        f'commit_url: "https://github.com/acquire-framework/'
        f'acquire-framework.github.io/tree/{commit}"',
    ]
    (ROOT / "_variables.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Banner shown only on the immutable versioned copies, so a reader who
    # arrives at /v26.7/ from a citation knows they are looking at a fixed
    # snapshot rather than current guidance. Written empty for root builds so
    # the include is unconditional.
    if is_release:
        banner = (
            '<div class="acq-version-banner" role="note">'
            f"<strong>Version {version}</strong> — a fixed snapshot, built "
            f'{build_date()} from commit <code>{short}</code>. '
            "Thresholds and recipes change as evidence accumulates. "
            f'<a href="{SITE_URL}/">See the current version</a>.'
            "</div>"
        )
    else:
        banner = "<!-- development build: no version banner -->"
    (ROOT / "_banner.html").write_text(banner + "\n", encoding="utf-8")

    for line in lines[1:]:
        print(line)


if __name__ == "__main__":
    main()
